// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogMessage.proto

package de.cf.autoscaler.kafka.protobuf;

public final class ProtobufLogMessageWrapper {
  private ProtobufLogMessageWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoLogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autoscaler.ProtoLogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>bytes logMessage = 2;</code>
     */
    com.google.protobuf.ByteString getLogMessage();

    /**
     * <code>string logMessageType = 3;</code>
     */
    java.lang.String getLogMessageType();
    /**
     * <code>string logMessageType = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogMessageTypeBytes();

    /**
     * <code>string appId = 4;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string appId = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();
  }
  /**
   * Protobuf type {@code autoscaler.ProtoLogMessage}
   */
  public  static final class ProtoLogMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:autoscaler.ProtoLogMessage)
      ProtoLogMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoLogMessage.newBuilder() to construct.
    private ProtoLogMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoLogMessage() {
      timestamp_ = 0L;
      logMessage_ = com.google.protobuf.ByteString.EMPTY;
      logMessageType_ = "";
      appId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoLogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {

              logMessage_ = input.readBytes();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              logMessageType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.internal_static_autoscaler_ProtoLogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.internal_static_autoscaler_ProtoLogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.class, de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LOGMESSAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString logMessage_;
    /**
     * <code>bytes logMessage = 2;</code>
     */
    public com.google.protobuf.ByteString getLogMessage() {
      return logMessage_;
    }

    public static final int LOGMESSAGETYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object logMessageType_;
    /**
     * <code>string logMessageType = 3;</code>
     */
    public java.lang.String getLogMessageType() {
      java.lang.Object ref = logMessageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logMessageType_ = s;
        return s;
      }
    }
    /**
     * <code>string logMessageType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogMessageTypeBytes() {
      java.lang.Object ref = logMessageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logMessageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPID_FIELD_NUMBER = 4;
    private volatile java.lang.Object appId_;
    /**
     * <code>string appId = 4;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string appId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!logMessage_.isEmpty()) {
        output.writeBytes(2, logMessage_);
      }
      if (!getLogMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, logMessageType_);
      }
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, appId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!logMessage_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, logMessage_);
      }
      if (!getLogMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, logMessageType_);
      }
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, appId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage)) {
        return super.equals(obj);
      }
      de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage other = (de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getLogMessage()
          .equals(other.getLogMessage());
      result = result && getLogMessageType()
          .equals(other.getLogMessageType());
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + LOGMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLogMessage().hashCode();
      hash = (37 * hash) + LOGMESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLogMessageType().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code autoscaler.ProtoLogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:autoscaler.ProtoLogMessage)
        de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.internal_static_autoscaler_ProtoLogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.internal_static_autoscaler_ProtoLogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.class, de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.Builder.class);
      }

      // Construct using de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        logMessage_ = com.google.protobuf.ByteString.EMPTY;

        logMessageType_ = "";

        appId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.internal_static_autoscaler_ProtoLogMessage_descriptor;
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage getDefaultInstanceForType() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.getDefaultInstance();
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage build() {
        de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage buildPartial() {
        de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage result = new de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage(this);
        result.timestamp_ = timestamp_;
        result.logMessage_ = logMessage_;
        result.logMessageType_ = logMessageType_;
        result.appId_ = appId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage) {
          return mergeFrom((de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage other) {
        if (other == de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getLogMessage() != com.google.protobuf.ByteString.EMPTY) {
          setLogMessage(other.getLogMessage());
        }
        if (!other.getLogMessageType().isEmpty()) {
          logMessageType_ = other.logMessageType_;
          onChanged();
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString logMessage_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes logMessage = 2;</code>
       */
      public com.google.protobuf.ByteString getLogMessage() {
        return logMessage_;
      }
      /**
       * <code>bytes logMessage = 2;</code>
       */
      public Builder setLogMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes logMessage = 2;</code>
       */
      public Builder clearLogMessage() {
        
        logMessage_ = getDefaultInstance().getLogMessage();
        onChanged();
        return this;
      }

      private java.lang.Object logMessageType_ = "";
      /**
       * <code>string logMessageType = 3;</code>
       */
      public java.lang.String getLogMessageType() {
        java.lang.Object ref = logMessageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logMessageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string logMessageType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogMessageTypeBytes() {
        java.lang.Object ref = logMessageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logMessageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string logMessageType = 3;</code>
       */
      public Builder setLogMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logMessageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string logMessageType = 3;</code>
       */
      public Builder clearLogMessageType() {
        
        logMessageType_ = getDefaultInstance().getLogMessageType();
        onChanged();
        return this;
      }
      /**
       * <code>string logMessageType = 3;</code>
       */
      public Builder setLogMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logMessageType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string appId = 4;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appId = 4;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 4;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 4;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:autoscaler.ProtoLogMessage)
    }

    // @@protoc_insertion_point(class_scope:autoscaler.ProtoLogMessage)
    private static final de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage();
    }

    public static de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoLogMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtoLogMessage>() {
      public ProtoLogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoLogMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoLogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoLogMessage> getParserForType() {
      return PARSER;
    }

    public de.cf.autoscaler.kafka.protobuf.ProtobufLogMessageWrapper.ProtoLogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autoscaler_ProtoLogMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autoscaler_ProtoLogMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020LogMessage.proto\022\nautoscaler\"_\n\017ProtoL" +
      "ogMessage\022\021\n\ttimestamp\030\001 \001(\003\022\022\n\nlogMessa" +
      "ge\030\002 \001(\014\022\026\n\016logMessageType\030\003 \001(\t\022\r\n\005appI" +
      "d\030\004 \001(\tBi\n\037de.cf.autoscaler.kafka.protob" +
      "ufB\031ProtobufLogMessageWrapper\252\002*de.cf.au" +
      "toscaler.ProtobufLogMessageWrapperb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_autoscaler_ProtoLogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autoscaler_ProtoLogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autoscaler_ProtoLogMessage_descriptor,
        new java.lang.String[] { "Timestamp", "LogMessage", "LogMessageType", "AppId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
