// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScalingLog.proto

package de.cf.autoscaler.kafka.protobuf;

public final class ProtobufScalingLogWrapper {
  private ProtobufScalingLogWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoScalingLogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autoscaler.ProtoScalingLog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>string appId = 2;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string appId = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string resourceName = 3;</code>
     */
    java.lang.String getResourceName();
    /**
     * <code>string resourceName = 3;</code>
     */
    com.google.protobuf.ByteString
        getResourceNameBytes();

    /**
     * <code>int32 component = 4;</code>
     */
    int getComponent();

    /**
     * <code>int32 oldInstances = 5;</code>
     */
    int getOldInstances();

    /**
     * <code>int32 newInstances = 6;</code>
     */
    int getNewInstances();

    /**
     * <code>int32 currentMaxInstanceLimit = 7;</code>
     */
    int getCurrentMaxInstanceLimit();

    /**
     * <code>int32 currentMinInstanceLimit = 8;</code>
     */
    int getCurrentMinInstanceLimit();

    /**
     * <code>int32 currentCpuLoad = 9;</code>
     */
    int getCurrentCpuLoad();

    /**
     * <code>int32 currentCpuUpperLimit = 10;</code>
     */
    int getCurrentCpuUpperLimit();

    /**
     * <code>int32 currentCpuLowerLimit = 11;</code>
     */
    int getCurrentCpuLowerLimit();

    /**
     * <code>int64 currentRamLoad = 12;</code>
     */
    long getCurrentRamLoad();

    /**
     * <code>int64 currentRamUpperLimit = 13;</code>
     */
    long getCurrentRamUpperLimit();

    /**
     * <code>int64 currentRamLowerLimit = 14;</code>
     */
    long getCurrentRamLowerLimit();

    /**
     * <code>int32 currentRequestCount = 15;</code>
     */
    int getCurrentRequestCount();

    /**
     * <code>int32 currentLatencyValue = 16;</code>
     */
    int getCurrentLatencyValue();

    /**
     * <code>int32 currentLatencyUpperLimit = 17;</code>
     */
    int getCurrentLatencyUpperLimit();

    /**
     * <code>int32 currentLatencyLowerLimit = 18;</code>
     */
    int getCurrentLatencyLowerLimit();

    /**
     * <code>int32 currentQuotientValue = 19;</code>
     */
    int getCurrentQuotientValue();

    /**
     * <code>int32 httpStatusCode = 20;</code>
     */
    int getHttpStatusCode();

    /**
     * <code>string httpStatusText = 21;</code>
     */
    java.lang.String getHttpStatusText();
    /**
     * <code>string httpStatusText = 21;</code>
     */
    com.google.protobuf.ByteString
        getHttpStatusTextBytes();

    /**
     * <code>string description = 22;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 22;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code autoscaler.ProtoScalingLog}
   */
  public  static final class ProtoScalingLog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:autoscaler.ProtoScalingLog)
      ProtoScalingLogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoScalingLog.newBuilder() to construct.
    private ProtoScalingLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoScalingLog() {
      timestamp_ = 0L;
      appId_ = "";
      resourceName_ = "";
      component_ = 0;
      oldInstances_ = 0;
      newInstances_ = 0;
      currentMaxInstanceLimit_ = 0;
      currentMinInstanceLimit_ = 0;
      currentCpuLoad_ = 0;
      currentCpuUpperLimit_ = 0;
      currentCpuLowerLimit_ = 0;
      currentRamLoad_ = 0L;
      currentRamUpperLimit_ = 0L;
      currentRamLowerLimit_ = 0L;
      currentRequestCount_ = 0;
      currentLatencyValue_ = 0;
      currentLatencyUpperLimit_ = 0;
      currentLatencyLowerLimit_ = 0;
      currentQuotientValue_ = 0;
      httpStatusCode_ = 0;
      httpStatusText_ = "";
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoScalingLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timestamp_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              resourceName_ = s;
              break;
            }
            case 32: {

              component_ = input.readInt32();
              break;
            }
            case 40: {

              oldInstances_ = input.readInt32();
              break;
            }
            case 48: {

              newInstances_ = input.readInt32();
              break;
            }
            case 56: {

              currentMaxInstanceLimit_ = input.readInt32();
              break;
            }
            case 64: {

              currentMinInstanceLimit_ = input.readInt32();
              break;
            }
            case 72: {

              currentCpuLoad_ = input.readInt32();
              break;
            }
            case 80: {

              currentCpuUpperLimit_ = input.readInt32();
              break;
            }
            case 88: {

              currentCpuLowerLimit_ = input.readInt32();
              break;
            }
            case 96: {

              currentRamLoad_ = input.readInt64();
              break;
            }
            case 104: {

              currentRamUpperLimit_ = input.readInt64();
              break;
            }
            case 112: {

              currentRamLowerLimit_ = input.readInt64();
              break;
            }
            case 120: {

              currentRequestCount_ = input.readInt32();
              break;
            }
            case 128: {

              currentLatencyValue_ = input.readInt32();
              break;
            }
            case 136: {

              currentLatencyUpperLimit_ = input.readInt32();
              break;
            }
            case 144: {

              currentLatencyLowerLimit_ = input.readInt32();
              break;
            }
            case 152: {

              currentQuotientValue_ = input.readInt32();
              break;
            }
            case 160: {

              httpStatusCode_ = input.readInt32();
              break;
            }
            case 170: {
              java.lang.String s = input.readStringRequireUtf8();

              httpStatusText_ = s;
              break;
            }
            case 178: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.internal_static_autoscaler_ProtoScalingLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.internal_static_autoscaler_ProtoScalingLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.class, de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object appId_;
    /**
     * <code>string appId = 2;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string appId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESOURCENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object resourceName_;
    /**
     * <code>string resourceName = 3;</code>
     */
    public java.lang.String getResourceName() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceName_ = s;
        return s;
      }
    }
    /**
     * <code>string resourceName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResourceNameBytes() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENT_FIELD_NUMBER = 4;
    private int component_;
    /**
     * <code>int32 component = 4;</code>
     */
    public int getComponent() {
      return component_;
    }

    public static final int OLDINSTANCES_FIELD_NUMBER = 5;
    private int oldInstances_;
    /**
     * <code>int32 oldInstances = 5;</code>
     */
    public int getOldInstances() {
      return oldInstances_;
    }

    public static final int NEWINSTANCES_FIELD_NUMBER = 6;
    private int newInstances_;
    /**
     * <code>int32 newInstances = 6;</code>
     */
    public int getNewInstances() {
      return newInstances_;
    }

    public static final int CURRENTMAXINSTANCELIMIT_FIELD_NUMBER = 7;
    private int currentMaxInstanceLimit_;
    /**
     * <code>int32 currentMaxInstanceLimit = 7;</code>
     */
    public int getCurrentMaxInstanceLimit() {
      return currentMaxInstanceLimit_;
    }

    public static final int CURRENTMININSTANCELIMIT_FIELD_NUMBER = 8;
    private int currentMinInstanceLimit_;
    /**
     * <code>int32 currentMinInstanceLimit = 8;</code>
     */
    public int getCurrentMinInstanceLimit() {
      return currentMinInstanceLimit_;
    }

    public static final int CURRENTCPULOAD_FIELD_NUMBER = 9;
    private int currentCpuLoad_;
    /**
     * <code>int32 currentCpuLoad = 9;</code>
     */
    public int getCurrentCpuLoad() {
      return currentCpuLoad_;
    }

    public static final int CURRENTCPUUPPERLIMIT_FIELD_NUMBER = 10;
    private int currentCpuUpperLimit_;
    /**
     * <code>int32 currentCpuUpperLimit = 10;</code>
     */
    public int getCurrentCpuUpperLimit() {
      return currentCpuUpperLimit_;
    }

    public static final int CURRENTCPULOWERLIMIT_FIELD_NUMBER = 11;
    private int currentCpuLowerLimit_;
    /**
     * <code>int32 currentCpuLowerLimit = 11;</code>
     */
    public int getCurrentCpuLowerLimit() {
      return currentCpuLowerLimit_;
    }

    public static final int CURRENTRAMLOAD_FIELD_NUMBER = 12;
    private long currentRamLoad_;
    /**
     * <code>int64 currentRamLoad = 12;</code>
     */
    public long getCurrentRamLoad() {
      return currentRamLoad_;
    }

    public static final int CURRENTRAMUPPERLIMIT_FIELD_NUMBER = 13;
    private long currentRamUpperLimit_;
    /**
     * <code>int64 currentRamUpperLimit = 13;</code>
     */
    public long getCurrentRamUpperLimit() {
      return currentRamUpperLimit_;
    }

    public static final int CURRENTRAMLOWERLIMIT_FIELD_NUMBER = 14;
    private long currentRamLowerLimit_;
    /**
     * <code>int64 currentRamLowerLimit = 14;</code>
     */
    public long getCurrentRamLowerLimit() {
      return currentRamLowerLimit_;
    }

    public static final int CURRENTREQUESTCOUNT_FIELD_NUMBER = 15;
    private int currentRequestCount_;
    /**
     * <code>int32 currentRequestCount = 15;</code>
     */
    public int getCurrentRequestCount() {
      return currentRequestCount_;
    }

    public static final int CURRENTLATENCYVALUE_FIELD_NUMBER = 16;
    private int currentLatencyValue_;
    /**
     * <code>int32 currentLatencyValue = 16;</code>
     */
    public int getCurrentLatencyValue() {
      return currentLatencyValue_;
    }

    public static final int CURRENTLATENCYUPPERLIMIT_FIELD_NUMBER = 17;
    private int currentLatencyUpperLimit_;
    /**
     * <code>int32 currentLatencyUpperLimit = 17;</code>
     */
    public int getCurrentLatencyUpperLimit() {
      return currentLatencyUpperLimit_;
    }

    public static final int CURRENTLATENCYLOWERLIMIT_FIELD_NUMBER = 18;
    private int currentLatencyLowerLimit_;
    /**
     * <code>int32 currentLatencyLowerLimit = 18;</code>
     */
    public int getCurrentLatencyLowerLimit() {
      return currentLatencyLowerLimit_;
    }

    public static final int CURRENTQUOTIENTVALUE_FIELD_NUMBER = 19;
    private int currentQuotientValue_;
    /**
     * <code>int32 currentQuotientValue = 19;</code>
     */
    public int getCurrentQuotientValue() {
      return currentQuotientValue_;
    }

    public static final int HTTPSTATUSCODE_FIELD_NUMBER = 20;
    private int httpStatusCode_;
    /**
     * <code>int32 httpStatusCode = 20;</code>
     */
    public int getHttpStatusCode() {
      return httpStatusCode_;
    }

    public static final int HTTPSTATUSTEXT_FIELD_NUMBER = 21;
    private volatile java.lang.Object httpStatusText_;
    /**
     * <code>string httpStatusText = 21;</code>
     */
    public java.lang.String getHttpStatusText() {
      java.lang.Object ref = httpStatusText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpStatusText_ = s;
        return s;
      }
    }
    /**
     * <code>string httpStatusText = 21;</code>
     */
    public com.google.protobuf.ByteString
        getHttpStatusTextBytes() {
      java.lang.Object ref = httpStatusText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpStatusText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 22;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 22;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 22;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeInt64(1, timestamp_);
      }
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appId_);
      }
      if (!getResourceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resourceName_);
      }
      if (component_ != 0) {
        output.writeInt32(4, component_);
      }
      if (oldInstances_ != 0) {
        output.writeInt32(5, oldInstances_);
      }
      if (newInstances_ != 0) {
        output.writeInt32(6, newInstances_);
      }
      if (currentMaxInstanceLimit_ != 0) {
        output.writeInt32(7, currentMaxInstanceLimit_);
      }
      if (currentMinInstanceLimit_ != 0) {
        output.writeInt32(8, currentMinInstanceLimit_);
      }
      if (currentCpuLoad_ != 0) {
        output.writeInt32(9, currentCpuLoad_);
      }
      if (currentCpuUpperLimit_ != 0) {
        output.writeInt32(10, currentCpuUpperLimit_);
      }
      if (currentCpuLowerLimit_ != 0) {
        output.writeInt32(11, currentCpuLowerLimit_);
      }
      if (currentRamLoad_ != 0L) {
        output.writeInt64(12, currentRamLoad_);
      }
      if (currentRamUpperLimit_ != 0L) {
        output.writeInt64(13, currentRamUpperLimit_);
      }
      if (currentRamLowerLimit_ != 0L) {
        output.writeInt64(14, currentRamLowerLimit_);
      }
      if (currentRequestCount_ != 0) {
        output.writeInt32(15, currentRequestCount_);
      }
      if (currentLatencyValue_ != 0) {
        output.writeInt32(16, currentLatencyValue_);
      }
      if (currentLatencyUpperLimit_ != 0) {
        output.writeInt32(17, currentLatencyUpperLimit_);
      }
      if (currentLatencyLowerLimit_ != 0) {
        output.writeInt32(18, currentLatencyLowerLimit_);
      }
      if (currentQuotientValue_ != 0) {
        output.writeInt32(19, currentQuotientValue_);
      }
      if (httpStatusCode_ != 0) {
        output.writeInt32(20, httpStatusCode_);
      }
      if (!getHttpStatusTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, httpStatusText_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 22, description_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appId_);
      }
      if (!getResourceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resourceName_);
      }
      if (component_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, component_);
      }
      if (oldInstances_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, oldInstances_);
      }
      if (newInstances_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, newInstances_);
      }
      if (currentMaxInstanceLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, currentMaxInstanceLimit_);
      }
      if (currentMinInstanceLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, currentMinInstanceLimit_);
      }
      if (currentCpuLoad_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, currentCpuLoad_);
      }
      if (currentCpuUpperLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, currentCpuUpperLimit_);
      }
      if (currentCpuLowerLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, currentCpuLowerLimit_);
      }
      if (currentRamLoad_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, currentRamLoad_);
      }
      if (currentRamUpperLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, currentRamUpperLimit_);
      }
      if (currentRamLowerLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, currentRamLowerLimit_);
      }
      if (currentRequestCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, currentRequestCount_);
      }
      if (currentLatencyValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, currentLatencyValue_);
      }
      if (currentLatencyUpperLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, currentLatencyUpperLimit_);
      }
      if (currentLatencyLowerLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, currentLatencyLowerLimit_);
      }
      if (currentQuotientValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, currentQuotientValue_);
      }
      if (httpStatusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, httpStatusCode_);
      }
      if (!getHttpStatusTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, httpStatusText_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog)) {
        return super.equals(obj);
      }
      de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog other = (de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && getResourceName()
          .equals(other.getResourceName());
      result = result && (getComponent()
          == other.getComponent());
      result = result && (getOldInstances()
          == other.getOldInstances());
      result = result && (getNewInstances()
          == other.getNewInstances());
      result = result && (getCurrentMaxInstanceLimit()
          == other.getCurrentMaxInstanceLimit());
      result = result && (getCurrentMinInstanceLimit()
          == other.getCurrentMinInstanceLimit());
      result = result && (getCurrentCpuLoad()
          == other.getCurrentCpuLoad());
      result = result && (getCurrentCpuUpperLimit()
          == other.getCurrentCpuUpperLimit());
      result = result && (getCurrentCpuLowerLimit()
          == other.getCurrentCpuLowerLimit());
      result = result && (getCurrentRamLoad()
          == other.getCurrentRamLoad());
      result = result && (getCurrentRamUpperLimit()
          == other.getCurrentRamUpperLimit());
      result = result && (getCurrentRamLowerLimit()
          == other.getCurrentRamLowerLimit());
      result = result && (getCurrentRequestCount()
          == other.getCurrentRequestCount());
      result = result && (getCurrentLatencyValue()
          == other.getCurrentLatencyValue());
      result = result && (getCurrentLatencyUpperLimit()
          == other.getCurrentLatencyUpperLimit());
      result = result && (getCurrentLatencyLowerLimit()
          == other.getCurrentLatencyLowerLimit());
      result = result && (getCurrentQuotientValue()
          == other.getCurrentQuotientValue());
      result = result && (getHttpStatusCode()
          == other.getHttpStatusCode());
      result = result && getHttpStatusText()
          .equals(other.getHttpStatusText());
      result = result && getDescription()
          .equals(other.getDescription());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + RESOURCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getResourceName().hashCode();
      hash = (37 * hash) + COMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getComponent();
      hash = (37 * hash) + OLDINSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getOldInstances();
      hash = (37 * hash) + NEWINSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getNewInstances();
      hash = (37 * hash) + CURRENTMAXINSTANCELIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentMaxInstanceLimit();
      hash = (37 * hash) + CURRENTMININSTANCELIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentMinInstanceLimit();
      hash = (37 * hash) + CURRENTCPULOAD_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentCpuLoad();
      hash = (37 * hash) + CURRENTCPUUPPERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentCpuUpperLimit();
      hash = (37 * hash) + CURRENTCPULOWERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentCpuLowerLimit();
      hash = (37 * hash) + CURRENTRAMLOAD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentRamLoad());
      hash = (37 * hash) + CURRENTRAMUPPERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentRamUpperLimit());
      hash = (37 * hash) + CURRENTRAMLOWERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentRamLowerLimit());
      hash = (37 * hash) + CURRENTREQUESTCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRequestCount();
      hash = (37 * hash) + CURRENTLATENCYVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentLatencyValue();
      hash = (37 * hash) + CURRENTLATENCYUPPERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentLatencyUpperLimit();
      hash = (37 * hash) + CURRENTLATENCYLOWERLIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentLatencyLowerLimit();
      hash = (37 * hash) + CURRENTQUOTIENTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentQuotientValue();
      hash = (37 * hash) + HTTPSTATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getHttpStatusCode();
      hash = (37 * hash) + HTTPSTATUSTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getHttpStatusText().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code autoscaler.ProtoScalingLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:autoscaler.ProtoScalingLog)
        de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.internal_static_autoscaler_ProtoScalingLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.internal_static_autoscaler_ProtoScalingLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.class, de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.Builder.class);
      }

      // Construct using de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        appId_ = "";

        resourceName_ = "";

        component_ = 0;

        oldInstances_ = 0;

        newInstances_ = 0;

        currentMaxInstanceLimit_ = 0;

        currentMinInstanceLimit_ = 0;

        currentCpuLoad_ = 0;

        currentCpuUpperLimit_ = 0;

        currentCpuLowerLimit_ = 0;

        currentRamLoad_ = 0L;

        currentRamUpperLimit_ = 0L;

        currentRamLowerLimit_ = 0L;

        currentRequestCount_ = 0;

        currentLatencyValue_ = 0;

        currentLatencyUpperLimit_ = 0;

        currentLatencyLowerLimit_ = 0;

        currentQuotientValue_ = 0;

        httpStatusCode_ = 0;

        httpStatusText_ = "";

        description_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.internal_static_autoscaler_ProtoScalingLog_descriptor;
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog getDefaultInstanceForType() {
        return de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.getDefaultInstance();
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog build() {
        de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog buildPartial() {
        de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog result = new de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog(this);
        result.timestamp_ = timestamp_;
        result.appId_ = appId_;
        result.resourceName_ = resourceName_;
        result.component_ = component_;
        result.oldInstances_ = oldInstances_;
        result.newInstances_ = newInstances_;
        result.currentMaxInstanceLimit_ = currentMaxInstanceLimit_;
        result.currentMinInstanceLimit_ = currentMinInstanceLimit_;
        result.currentCpuLoad_ = currentCpuLoad_;
        result.currentCpuUpperLimit_ = currentCpuUpperLimit_;
        result.currentCpuLowerLimit_ = currentCpuLowerLimit_;
        result.currentRamLoad_ = currentRamLoad_;
        result.currentRamUpperLimit_ = currentRamUpperLimit_;
        result.currentRamLowerLimit_ = currentRamLowerLimit_;
        result.currentRequestCount_ = currentRequestCount_;
        result.currentLatencyValue_ = currentLatencyValue_;
        result.currentLatencyUpperLimit_ = currentLatencyUpperLimit_;
        result.currentLatencyLowerLimit_ = currentLatencyLowerLimit_;
        result.currentQuotientValue_ = currentQuotientValue_;
        result.httpStatusCode_ = httpStatusCode_;
        result.httpStatusText_ = httpStatusText_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog) {
          return mergeFrom((de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog other) {
        if (other == de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getResourceName().isEmpty()) {
          resourceName_ = other.resourceName_;
          onChanged();
        }
        if (other.getComponent() != 0) {
          setComponent(other.getComponent());
        }
        if (other.getOldInstances() != 0) {
          setOldInstances(other.getOldInstances());
        }
        if (other.getNewInstances() != 0) {
          setNewInstances(other.getNewInstances());
        }
        if (other.getCurrentMaxInstanceLimit() != 0) {
          setCurrentMaxInstanceLimit(other.getCurrentMaxInstanceLimit());
        }
        if (other.getCurrentMinInstanceLimit() != 0) {
          setCurrentMinInstanceLimit(other.getCurrentMinInstanceLimit());
        }
        if (other.getCurrentCpuLoad() != 0) {
          setCurrentCpuLoad(other.getCurrentCpuLoad());
        }
        if (other.getCurrentCpuUpperLimit() != 0) {
          setCurrentCpuUpperLimit(other.getCurrentCpuUpperLimit());
        }
        if (other.getCurrentCpuLowerLimit() != 0) {
          setCurrentCpuLowerLimit(other.getCurrentCpuLowerLimit());
        }
        if (other.getCurrentRamLoad() != 0L) {
          setCurrentRamLoad(other.getCurrentRamLoad());
        }
        if (other.getCurrentRamUpperLimit() != 0L) {
          setCurrentRamUpperLimit(other.getCurrentRamUpperLimit());
        }
        if (other.getCurrentRamLowerLimit() != 0L) {
          setCurrentRamLowerLimit(other.getCurrentRamLowerLimit());
        }
        if (other.getCurrentRequestCount() != 0) {
          setCurrentRequestCount(other.getCurrentRequestCount());
        }
        if (other.getCurrentLatencyValue() != 0) {
          setCurrentLatencyValue(other.getCurrentLatencyValue());
        }
        if (other.getCurrentLatencyUpperLimit() != 0) {
          setCurrentLatencyUpperLimit(other.getCurrentLatencyUpperLimit());
        }
        if (other.getCurrentLatencyLowerLimit() != 0) {
          setCurrentLatencyLowerLimit(other.getCurrentLatencyLowerLimit());
        }
        if (other.getCurrentQuotientValue() != 0) {
          setCurrentQuotientValue(other.getCurrentQuotientValue());
        }
        if (other.getHttpStatusCode() != 0) {
          setHttpStatusCode(other.getHttpStatusCode());
        }
        if (!other.getHttpStatusText().isEmpty()) {
          httpStatusText_ = other.httpStatusText_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string appId = 2;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 2;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object resourceName_ = "";
      /**
       * <code>string resourceName = 3;</code>
       */
      public java.lang.String getResourceName() {
        java.lang.Object ref = resourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resourceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string resourceName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResourceNameBytes() {
        java.lang.Object ref = resourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resourceName = 3;</code>
       */
      public Builder setResourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resourceName = 3;</code>
       */
      public Builder clearResourceName() {
        
        resourceName_ = getDefaultInstance().getResourceName();
        onChanged();
        return this;
      }
      /**
       * <code>string resourceName = 3;</code>
       */
      public Builder setResourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resourceName_ = value;
        onChanged();
        return this;
      }

      private int component_ ;
      /**
       * <code>int32 component = 4;</code>
       */
      public int getComponent() {
        return component_;
      }
      /**
       * <code>int32 component = 4;</code>
       */
      public Builder setComponent(int value) {
        
        component_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 component = 4;</code>
       */
      public Builder clearComponent() {
        
        component_ = 0;
        onChanged();
        return this;
      }

      private int oldInstances_ ;
      /**
       * <code>int32 oldInstances = 5;</code>
       */
      public int getOldInstances() {
        return oldInstances_;
      }
      /**
       * <code>int32 oldInstances = 5;</code>
       */
      public Builder setOldInstances(int value) {
        
        oldInstances_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 oldInstances = 5;</code>
       */
      public Builder clearOldInstances() {
        
        oldInstances_ = 0;
        onChanged();
        return this;
      }

      private int newInstances_ ;
      /**
       * <code>int32 newInstances = 6;</code>
       */
      public int getNewInstances() {
        return newInstances_;
      }
      /**
       * <code>int32 newInstances = 6;</code>
       */
      public Builder setNewInstances(int value) {
        
        newInstances_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 newInstances = 6;</code>
       */
      public Builder clearNewInstances() {
        
        newInstances_ = 0;
        onChanged();
        return this;
      }

      private int currentMaxInstanceLimit_ ;
      /**
       * <code>int32 currentMaxInstanceLimit = 7;</code>
       */
      public int getCurrentMaxInstanceLimit() {
        return currentMaxInstanceLimit_;
      }
      /**
       * <code>int32 currentMaxInstanceLimit = 7;</code>
       */
      public Builder setCurrentMaxInstanceLimit(int value) {
        
        currentMaxInstanceLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentMaxInstanceLimit = 7;</code>
       */
      public Builder clearCurrentMaxInstanceLimit() {
        
        currentMaxInstanceLimit_ = 0;
        onChanged();
        return this;
      }

      private int currentMinInstanceLimit_ ;
      /**
       * <code>int32 currentMinInstanceLimit = 8;</code>
       */
      public int getCurrentMinInstanceLimit() {
        return currentMinInstanceLimit_;
      }
      /**
       * <code>int32 currentMinInstanceLimit = 8;</code>
       */
      public Builder setCurrentMinInstanceLimit(int value) {
        
        currentMinInstanceLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentMinInstanceLimit = 8;</code>
       */
      public Builder clearCurrentMinInstanceLimit() {
        
        currentMinInstanceLimit_ = 0;
        onChanged();
        return this;
      }

      private int currentCpuLoad_ ;
      /**
       * <code>int32 currentCpuLoad = 9;</code>
       */
      public int getCurrentCpuLoad() {
        return currentCpuLoad_;
      }
      /**
       * <code>int32 currentCpuLoad = 9;</code>
       */
      public Builder setCurrentCpuLoad(int value) {
        
        currentCpuLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentCpuLoad = 9;</code>
       */
      public Builder clearCurrentCpuLoad() {
        
        currentCpuLoad_ = 0;
        onChanged();
        return this;
      }

      private int currentCpuUpperLimit_ ;
      /**
       * <code>int32 currentCpuUpperLimit = 10;</code>
       */
      public int getCurrentCpuUpperLimit() {
        return currentCpuUpperLimit_;
      }
      /**
       * <code>int32 currentCpuUpperLimit = 10;</code>
       */
      public Builder setCurrentCpuUpperLimit(int value) {
        
        currentCpuUpperLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentCpuUpperLimit = 10;</code>
       */
      public Builder clearCurrentCpuUpperLimit() {
        
        currentCpuUpperLimit_ = 0;
        onChanged();
        return this;
      }

      private int currentCpuLowerLimit_ ;
      /**
       * <code>int32 currentCpuLowerLimit = 11;</code>
       */
      public int getCurrentCpuLowerLimit() {
        return currentCpuLowerLimit_;
      }
      /**
       * <code>int32 currentCpuLowerLimit = 11;</code>
       */
      public Builder setCurrentCpuLowerLimit(int value) {
        
        currentCpuLowerLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentCpuLowerLimit = 11;</code>
       */
      public Builder clearCurrentCpuLowerLimit() {
        
        currentCpuLowerLimit_ = 0;
        onChanged();
        return this;
      }

      private long currentRamLoad_ ;
      /**
       * <code>int64 currentRamLoad = 12;</code>
       */
      public long getCurrentRamLoad() {
        return currentRamLoad_;
      }
      /**
       * <code>int64 currentRamLoad = 12;</code>
       */
      public Builder setCurrentRamLoad(long value) {
        
        currentRamLoad_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currentRamLoad = 12;</code>
       */
      public Builder clearCurrentRamLoad() {
        
        currentRamLoad_ = 0L;
        onChanged();
        return this;
      }

      private long currentRamUpperLimit_ ;
      /**
       * <code>int64 currentRamUpperLimit = 13;</code>
       */
      public long getCurrentRamUpperLimit() {
        return currentRamUpperLimit_;
      }
      /**
       * <code>int64 currentRamUpperLimit = 13;</code>
       */
      public Builder setCurrentRamUpperLimit(long value) {
        
        currentRamUpperLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currentRamUpperLimit = 13;</code>
       */
      public Builder clearCurrentRamUpperLimit() {
        
        currentRamUpperLimit_ = 0L;
        onChanged();
        return this;
      }

      private long currentRamLowerLimit_ ;
      /**
       * <code>int64 currentRamLowerLimit = 14;</code>
       */
      public long getCurrentRamLowerLimit() {
        return currentRamLowerLimit_;
      }
      /**
       * <code>int64 currentRamLowerLimit = 14;</code>
       */
      public Builder setCurrentRamLowerLimit(long value) {
        
        currentRamLowerLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 currentRamLowerLimit = 14;</code>
       */
      public Builder clearCurrentRamLowerLimit() {
        
        currentRamLowerLimit_ = 0L;
        onChanged();
        return this;
      }

      private int currentRequestCount_ ;
      /**
       * <code>int32 currentRequestCount = 15;</code>
       */
      public int getCurrentRequestCount() {
        return currentRequestCount_;
      }
      /**
       * <code>int32 currentRequestCount = 15;</code>
       */
      public Builder setCurrentRequestCount(int value) {
        
        currentRequestCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentRequestCount = 15;</code>
       */
      public Builder clearCurrentRequestCount() {
        
        currentRequestCount_ = 0;
        onChanged();
        return this;
      }

      private int currentLatencyValue_ ;
      /**
       * <code>int32 currentLatencyValue = 16;</code>
       */
      public int getCurrentLatencyValue() {
        return currentLatencyValue_;
      }
      /**
       * <code>int32 currentLatencyValue = 16;</code>
       */
      public Builder setCurrentLatencyValue(int value) {
        
        currentLatencyValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentLatencyValue = 16;</code>
       */
      public Builder clearCurrentLatencyValue() {
        
        currentLatencyValue_ = 0;
        onChanged();
        return this;
      }

      private int currentLatencyUpperLimit_ ;
      /**
       * <code>int32 currentLatencyUpperLimit = 17;</code>
       */
      public int getCurrentLatencyUpperLimit() {
        return currentLatencyUpperLimit_;
      }
      /**
       * <code>int32 currentLatencyUpperLimit = 17;</code>
       */
      public Builder setCurrentLatencyUpperLimit(int value) {
        
        currentLatencyUpperLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentLatencyUpperLimit = 17;</code>
       */
      public Builder clearCurrentLatencyUpperLimit() {
        
        currentLatencyUpperLimit_ = 0;
        onChanged();
        return this;
      }

      private int currentLatencyLowerLimit_ ;
      /**
       * <code>int32 currentLatencyLowerLimit = 18;</code>
       */
      public int getCurrentLatencyLowerLimit() {
        return currentLatencyLowerLimit_;
      }
      /**
       * <code>int32 currentLatencyLowerLimit = 18;</code>
       */
      public Builder setCurrentLatencyLowerLimit(int value) {
        
        currentLatencyLowerLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentLatencyLowerLimit = 18;</code>
       */
      public Builder clearCurrentLatencyLowerLimit() {
        
        currentLatencyLowerLimit_ = 0;
        onChanged();
        return this;
      }

      private int currentQuotientValue_ ;
      /**
       * <code>int32 currentQuotientValue = 19;</code>
       */
      public int getCurrentQuotientValue() {
        return currentQuotientValue_;
      }
      /**
       * <code>int32 currentQuotientValue = 19;</code>
       */
      public Builder setCurrentQuotientValue(int value) {
        
        currentQuotientValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 currentQuotientValue = 19;</code>
       */
      public Builder clearCurrentQuotientValue() {
        
        currentQuotientValue_ = 0;
        onChanged();
        return this;
      }

      private int httpStatusCode_ ;
      /**
       * <code>int32 httpStatusCode = 20;</code>
       */
      public int getHttpStatusCode() {
        return httpStatusCode_;
      }
      /**
       * <code>int32 httpStatusCode = 20;</code>
       */
      public Builder setHttpStatusCode(int value) {
        
        httpStatusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 httpStatusCode = 20;</code>
       */
      public Builder clearHttpStatusCode() {
        
        httpStatusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object httpStatusText_ = "";
      /**
       * <code>string httpStatusText = 21;</code>
       */
      public java.lang.String getHttpStatusText() {
        java.lang.Object ref = httpStatusText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          httpStatusText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string httpStatusText = 21;</code>
       */
      public com.google.protobuf.ByteString
          getHttpStatusTextBytes() {
        java.lang.Object ref = httpStatusText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpStatusText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string httpStatusText = 21;</code>
       */
      public Builder setHttpStatusText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        httpStatusText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string httpStatusText = 21;</code>
       */
      public Builder clearHttpStatusText() {
        
        httpStatusText_ = getDefaultInstance().getHttpStatusText();
        onChanged();
        return this;
      }
      /**
       * <code>string httpStatusText = 21;</code>
       */
      public Builder setHttpStatusTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        httpStatusText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 22;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 22;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 22;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 22;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 22;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:autoscaler.ProtoScalingLog)
    }

    // @@protoc_insertion_point(class_scope:autoscaler.ProtoScalingLog)
    private static final de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog();
    }

    public static de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoScalingLog>
        PARSER = new com.google.protobuf.AbstractParser<ProtoScalingLog>() {
      public ProtoScalingLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoScalingLog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoScalingLog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoScalingLog> getParserForType() {
      return PARSER;
    }

    public de.cf.autoscaler.kafka.protobuf.ProtobufScalingLogWrapper.ProtoScalingLog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_autoscaler_ProtoScalingLog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_autoscaler_ProtoScalingLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ScalingLog.proto\022\nautoscaler\"\323\004\n\017Proto" +
      "ScalingLog\022\021\n\ttimestamp\030\001 \001(\003\022\r\n\005appId\030\002" +
      " \001(\t\022\024\n\014resourceName\030\003 \001(\t\022\021\n\tcomponent\030" +
      "\004 \001(\005\022\024\n\014oldInstances\030\005 \001(\005\022\024\n\014newInstan" +
      "ces\030\006 \001(\005\022\037\n\027currentMaxInstanceLimit\030\007 \001" +
      "(\005\022\037\n\027currentMinInstanceLimit\030\010 \001(\005\022\026\n\016c" +
      "urrentCpuLoad\030\t \001(\005\022\034\n\024currentCpuUpperLi" +
      "mit\030\n \001(\005\022\034\n\024currentCpuLowerLimit\030\013 \001(\005\022" +
      "\026\n\016currentRamLoad\030\014 \001(\003\022\034\n\024currentRamUpp" +
      "erLimit\030\r \001(\003\022\034\n\024currentRamLowerLimit\030\016 " +
      "\001(\003\022\033\n\023currentRequestCount\030\017 \001(\005\022\033\n\023curr" +
      "entLatencyValue\030\020 \001(\005\022 \n\030currentLatencyU" +
      "pperLimit\030\021 \001(\005\022 \n\030currentLatencyLowerLi" +
      "mit\030\022 \001(\005\022\034\n\024currentQuotientValue\030\023 \001(\005\022" +
      "\026\n\016httpStatusCode\030\024 \001(\005\022\026\n\016httpStatusTex" +
      "t\030\025 \001(\t\022\023\n\013description\030\026 \001(\tBi\n\037de.cf.au" +
      "toscaler.kafka.protobufB\031ProtobufScaling" +
      "LogWrapper\252\002*de.cf.autoscaler.ProtobufSc" +
      "alingLogWrapperb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_autoscaler_ProtoScalingLog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_autoscaler_ProtoScalingLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_autoscaler_ProtoScalingLog_descriptor,
        new java.lang.String[] { "Timestamp", "AppId", "ResourceName", "Component", "OldInstances", "NewInstances", "CurrentMaxInstanceLimit", "CurrentMinInstanceLimit", "CurrentCpuLoad", "CurrentCpuUpperLimit", "CurrentCpuLowerLimit", "CurrentRamLoad", "CurrentRamUpperLimit", "CurrentRamLowerLimit", "CurrentRequestCount", "CurrentLatencyValue", "CurrentLatencyUpperLimit", "CurrentLatencyLowerLimit", "CurrentQuotientValue", "HttpStatusCode", "HttpStatusText", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
